
public class library{
    enum jobs{
        director,
        producer,
        composer,
        operator,
        screenwriter,
        actor
    }
    enum genre{
        action,
        triller,
        horror,
        scifi,
        fantasy,
        drama,
        historic
    }
    static String[] roleVariants = new String[]{
        "Герой",
        "Влюбленный",
        "Проказник",
        "Шут",
        "Злодей",
        "Неизвестный",
        "Отщепенец",
        "Фат",
        "Моралист",
        "Опекун",
        "Друг",
        "Хвастун",
        "Блюститель порядка",
        "Ученый",
        "Вестник",

    }; 
    static String[] firstNameVariants = new String[] {
        "Габриеле",
        "Гавриил",
        "Гай",
        "Галактион",
        "Гарет",
        "Гаспар",
        "Гафур",
        "Гвидо",
        "Гейдар",
        "Геласий",
        "Гельмут",
        "Геннадий",
        "Генри",
        "Генрих",
        "Георге",
        "Георгий",
        "Гераклид",
        "Герберт",
        "Герман",
        "Германн",
        "Геронтий"};    
    static String[] surNameVariants = new String[] {
        "Абулафия",
        "Адырхаевы",
        "Арменинов",
        "Бабурин",
        "Бабуркин",
        "Баранов",
        "Бараш",
        "Бахтин",
        "Бенвенист",
        "Бердюгин",
        "Бернштейн",
        "Бессонов",
        "Боборыкин",
        "Боталов",
        "Вельмисов",
        "Виттманн",
        "Войнилович",
        "Волков",
        "Гагарин",
        "Гиззатуллин",
        "Ерохин"};  
    static String[] countryVariants = new String[] {
        "Австралия",
        "Австрия",
        "Азербайджан",
        "Албания",
        "Алжир",
        "Ангола",
        "Андорра",
        "Антигуа и Барбуда",
        "Аргентина",
        "Армения",
        "Афганистан",
        "Багамские Острова",
        "Бангладеш",
        "Барбадос",
        "Бахрейн",
        "Белорусь",
        "Белиз",
        "Бельгия",
        "Бенин",
        "Болгария"
    };

    static String[] name1Variants = new String[]{
        "Spicy",
        "Hot",
        "Quiet",
        "Expensive",
        "Young",
        "Steep",
        "Short",
        "High",
        "Long",
        "Sweet",
        "Strict",
        "Stone",
        "Cardinal",
        "Catastrophic",
        "Categorical",
        "Oathed",
        "Colossal",
        "Root",
        "Space",
        "Extreme",
        "Strong"
    };
    static String[] name2Variants = new String[]{
        "youth",
        "foreman",
        "servant",
        "uncle",
        "referee",
        "captain",
        "forester",
        "comrade",
        "steamboat",
        "freezing",
        "frost",
        "planetarium",
        "source",
        "city",
        "box",
        "human",
        "wind",
        "bread",
        "forest",
        "slipper",
        "smartphone"
    };
}