server:
  port: 8081

spring:
  application:
    name: Demo spring app
#  config:
#    activate: development
#---
#spring:
#  profiles: development
#server:
#  port: 9090
#---
#spring:
#  profiles: production
#server:
#  port: 9093